### ISSUE TITLE
A Non-Active user logging in throws an uncaught exception.

### ISSUE THREAD

**Issue by MomboMan** [fullstackhero/blazor-starter-kit#201] opened 2021-06-23 02:40 UTC
**Describe the bug**

**To Reproduce**
1. As the admin account, go to Users tab and click the ACTIONS drop down to edit the John Doe user.  Pick EDIT
2. In the Administrators Settings tab click the Active? toggle, turning off the toggle.
3. Log out of the Admin account.
4. Click the 'FILL BASIC USER CREDENTIALS'
5. Go to 'Developer Tools' in Chrome and see the error

**Expected behavior**
An error in the snackbar saying the 'User is not active, please contact an Admin'.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version 2.1

**Comment by neozhu** [comment] 2021-06-23 02:52
It seems that two conditions (active and email confirm) are equal to "true" for login

**Comment by iammukeshm** [comment] 2021-06-23 04:17
As the popular saying goes, "It's not a bug, It's a feature " 😆

**Comment by iammukeshm** [comment] 2021-06-23 05:13
What's the error you got?

I recreated the same steps you had mentioned. Here is what I see.

![image](https://user-images.githubusercontent.com/31455818/123039458-d0f13a00-d40f-11eb-88e6-2e227da81a41.png)

I checked the console log too. No unhandled exceptions were showing up.

**Comment by MomboMan** [comment] 2021-06-23 15:33
This:
![image](https://user-images.githubusercontent.com/45502389/123125395-b7e38b80-d405-11eb-87c1-38010a5c328a.png)

Maybe I have an older version?  ¯\_(ツ)_/¯

If yours works then just close this, I'm good.

Thanks

Craig

**Comment by iammukeshm** [comment] 2021-06-23 17:21
Yes, I think your code is a much older version. Closing for now.
Regards

**Closed as completed by iammukeshm** 2021-06-23 17:21 UTC
